BytePackager/packagecore

packagecore/dpkg.py, packagecore/pkgbuild.py, packagecore/rpm.py, test/packagecore.yaml
=> Add BP_UPGRADE environment variables to postinstall scripts

packagecore/builddata.py, packagecore/packager.py, test/packagecore.yaml
=> Rename 'pre' to 'precompile'

packagecore/distributions.py, packagecore/dpkg.py, packagecore/packager.py, packagecore/pkgbuild.py, packagecore/rpm.py, test/packagecore-tag.yaml
This changes the named output packages. This fixes #31, #30, and #27.
=> Add format strings for all packages

packagecore/__main__.py, packagecore/packager.py
=> Add -C option for source directory

packagecore/__main__.py
=> Print version at the start of each run

README.md, packagecore.yaml, packagecore/packager.py, packagecore/packager_test.py, test/packagecore.yaml
=> Fix meta syntax in readme and packagecore files and add unit test.

.gitignore, doc/01_intro.md, doc/03_yaml.md, doc/mkdocs.yml, mkdocs.yml
Closes #54 
Closes #32 
Closes #23
=> Part 2 of initial documentation in ReadTheDocs.

packagecore/configparser.py, packagecore/configparser_test.py, packagecore/packager.py
=> Create config parser class.

.travis.yml
=> Output packagecore-test* packages into tmp

packagecore/docker.py, packagecore/packager.py, test/packagecore.yaml
=> Fix testinstallcommands not being executed.

packagecore.yaml
=> Add setuptools as runtime dependency for all distributions

packagecore.yaml
=> Fix debian package creation

packagecore/rpm.py
=> Filter out duplicate files in rpm fix files script

.travis.yml
=> Run only single ubuntu build during tag pushes

packagecore/distributions.py, packagecore/packager.py, packagecore/rpm.py, packagecore/rpm_test.py, test/packagecore.yaml, test/test.c
=> Add opensuse support

packagecore/docker.py, packagecore/docker_test.py
=> Add unit test to docker.py

doc/04_yaml.md, packagecore/docker.py, packagecore/packager.py, packagecore/scriptfile.py, test/packagecore.yaml
=> Add BP_PACKAGE_FILE to environment.

packagecore/distributions.py, test/packagecore.yaml
=> Add fedora 26

packagecore/distributions.py
=> Fix debian package extension

.pylintrc, .travis.yml, packagecore/__main__.py, packagecore/builddata.py, packagecore/buildvariables.py, packagecore/buildvariables_test.py, packagecore/configfile.py, packagecore/configparser.py, packagecore/configparser_test.py, packagecore/distributions.py, packagecore/docker.py, packagecore/docker_test.py, packagecore/dpkg.py, packagecore/dpkg_test.py, packagecore/packager.py, packagecore/pkgbuild.py, packagecore/pkgbuild_test.py, packagecore/rpm.py, packagecore/rpm_test.py, packagecore/scriptfile.py, packagecore/scriptfile_test.py
=> Cleanup code to pass pylint

packagecore/packager.py
=> Rename package before installation

packagecore/rpm.py
=> Disable gpg check upon opensuse test install

README.md, doc/05_externalservice.md
=> Add 'sudo' to travis-ci examples for using pip

packagecore/distributions.py, test/packagecore.yaml
=> Add opensuse 42.3 to distributions

packagecore/__main__.py
=> Fix standalone options like --version and --distributions

.travis.yml, circle.yml, test/packagecore.yaml
=> Switch from 17.04 to 16.04 in PR tests

packagecore.yaml, packagecore/distributions.py, test/packagecore.yaml
=> Add fedora 28

packagecore/distributions.py
=> Switch to pritunl's arch linux image

.travis.yml, circle.yml, packagecore/dpkg.py, test/packagecore.yaml
=> Set apt-get to `noninteractive`.

packagecore/dpkg.py
=> Use force for link creation

doc/03_command.md
=> Add '--packages' to documentation

MANIFEST.in, setup.py
=> Use README.md as long description in setup.py

packagecore/distributions.py, test/packagecore.yaml
=> Add CentOS 7.5 and 7.6.

packagecore/distributions.py, test/packagecore.yaml
=> Add fedora 30 support

packagecore/distributions.py, test/packagecore.yaml
=> Add support for debian 10

.pylintrc, .travis.yml, packagecore/distributions.py, packagecore/rpm.py, test/packagecore.yaml
=> Add Centos8 support

packagecore/distributions.py, test/packagecore.yaml
=> Add support for Fedora 31

packagecore/configfile.py
See https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
=> Update yaml usage to use SafeLoader

packagecore/distributions.py, test/packagecore.yaml
=> Add fedora32 support.

packagecore/distributions.py, packagecore/rpm.py
=> Add support for opensuse tumbleweed

README.md, packagecore/distributions.py, test/packagecore.yaml
=> Add arch linux official image

.travis.yml, packagecore/distributions.py, packagecore/docker.py, packagecore/packager.py, packagecore/pkgbuild.py, test/packagecore.yaml
=> Fix arch linux build on travis CI

packagecore/distributions.py, test/packagecore.yaml
=> Add opensuse 15.2
